# For context, OpenSpiel is developed day-to-day using private continuous
# integration software.
#
# The current Travis CI setup is unpolished and verifies that open-source
# OpenSpiel builds correctly. This is done on a best-effort basis; we are not
# attached to Travis CI.
#
# If you use OpenSpiel, continuous integration improvements are welcome.
# Potential contributions include improving the CI configuration, using either
# Travis CI or another service (CircleCI, etc).

language: c

cache: pip
git:
  depth: 3

# We need to link against the shared C++ Python libraries. We will be using
# the system-wide python shared libraries and headers installed in install.sh.
# We assume the same Python version between the system wide Python, python-dev,
# and the virtualenv.
matrix:
  include:
  # Build and run tests without all optional dependencies (default behavior)
  - os: linux
    dist: bionic # Ubuntu 18.04.2 LTS released on 26 April 2018
    env: OS_PYTHON_VERSION=3.6
  # Build and run tests with all optional dependencies
  - os: linux
    dist: bionic # Ubuntu 18.04.2 LTS released on 26 April 2018
    env:
      - OS_PYTHON_VERSION=3.6
      - DEFAULT_OPTIONAL_DEPENDENCY="ON"
  # Build and test on MacOS. We use a single target, with all dependencies.
  - os: osx # macOS 10.14 (Mojave), release on September 24, 2018.
    osx_image: xcode10.3
    env:
      # Unfortunately, the build fails on MacOs for universal poker.
      - BUILD_WITH_ACPC="OFF"
      - DEFAULT_OPTIONAL_DEPENDENCY="ON"

script:
  - ./install.sh
  - python --version
  - ./open_spiel/scripts/travis_script.sh
