name: build_and_test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-24.04
          OS_PYTHON_VERSION: "3.12"
          DEFAULT_OPTIONAL_DEPENDENCY: "OFF"
          BUILD_SHARED_LIB: "OFF"
          OPEN_SPIEL_ABSL_VERSION: "20250127.1"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL: ""
        - os: macos-14
          OS_PYTHON_VERSION: "3.12"
          DEFAULT_OPTIONAL_DEPENDENCY: "OFF"
          BUILD_SHARED_LIB: "OFF"
          OPEN_SPIEL_ABSL_VERSION: "20250127.1"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL: ""
        - os: ubuntu-24.04
          OS_PYTHON_VERSION: "3.11"
          DEFAULT_OPTIONAL_DEPENDENCY: "ON"
          BUILD_SHARED_LIB: "OFF"
          OPEN_SPIEL_ABSL_VERSION: "20250127.1"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL: ""
        - os: ubuntu-24.04
          OS_PYTHON_VERSION: "3.10"
          DEFAULT_OPTIONAL_DEPENDENCY: "OFF"
          BUILD_SHARED_LIB: "OFF"
          OPEN_SPIEL_ABSL_VERSION: "20250127.1"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL: ""
        - os: macos-14
          OS_PYTHON_VERSION: "3.11"
          TRAVIS_USE_NOX: 0
          DEFAULT_OPTIONAL_DEPENDENCY: "OFF"
          BUILD_SHARED_LIB: "OFF"
          OPEN_SPIEL_ABSL_VERSION: "20250127.1"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL: ""

    runs-on: ${{ matrix.os }}
    env:
      OPEN_SPIEL_ENABLE_JAX: ON
      OPEN_SPIEL_ENABLE_PYTORCH: ON
      OPEN_SPIEL_ENABLE_PYTHON_MISC: ON
      OPEN_SPIEL_ABSL_VERSION: ${{ matrix.OPEN_SPIEL_ABSL_VERSION }}
      OS_PYTHON_VERSION: ${{ matrix.OS_PYTHON_VERSION }}
      DEFAULT_OPTIONAL_DEPENDENCY: ${{ matrix.DEFAULT_OPTIONAL_DEPENDENCY }}
      OPEN_SPIEL_BUILD_WITH_JULIA: ${{ matrix.OPEN_SPIEL_BUILD_WITH_JULIA }}
      BUILD_SHARED_LIB:  ${{ matrix.BUILD_SHARED_LIB }}
      OPEN_SPIEL_BUILD_WITH_ORTOOLS:  ${{ matrix.OPEN_SPIEL_BUILD_WITH_ORTOOLS }}
      OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL:  ${{ matrix.OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL }}

    steps:
      - name: Free Disk Space (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          echo "Disk space before cleanup:"
          df -h
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo docker image prune --all --force
          echo "Disk space after cleanup:"
          df -h

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.8'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.OS_PYTHON_VERSION }}
      - name: Ad-hoc fix
        if: ${{ matrix.DEFAULT_OPTIONAL_DEPENDENCY == 'ON' }}
        run: |
          # workaround for https://github.com/deepmind/open_spiel/issues/606
          sudo cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 $(julia --startup-file=no -e 'using Libdl;print(abspath(joinpath(Libdl.dlpath("libjulia"), "..", "julia")))')
      - name: Install
        run: |
          pwd
          ./open_spiel/scripts/ci_python_prechecks.sh
          chmod +x install.sh
          ./install.sh
      - name: Build and test
        run: |
          python3 --version
          ./open_spiel/scripts/ci_script.sh