name: build_and_test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        include:
        # Build and run tests without all optional dependencies (default behavior)
        # Ubuntu 18.04.2 LTS released on 26 April 2018
        - os: ubuntu-18.04
          OS_PYTHON_VERSION: 3.6
          TRAVIS_USE_NOX: 0
          DEFAULT_OPTIONAL_DEPENDENCY: "OFF"
          BUILD_SHARED_LIB: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL: ""
        - os: "ubuntu-20.04"
          OS_PYTHON_VERSION: 3.8
          TRAVIS_USE_NOX: 0
          DEFAULT_OPTIONAL_DEPENDENCY: "OFF"
          BUILD_SHARED_LIB: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL: ""
         # Build and run tests with all optional dependencies, including building a
         # shared library with linkable third party dependencies in place.
        - os: ubuntu-20.04
          DEFAULT_OPTIONAL_DEPENDENCY: "ON"
          TRAVIS_USE_NOX: 0
          BUILD_SHARED_LIB: "ON"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS: "ON"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL: "https://github.com/google/or-tools/releases/download/v8.0/or-tools_ubuntu-20.04_v8.0.8283.tar.gz"
         # macOS Catalina 10.15
        - os: macos-10.15
          OS_PYTHON_VERSION: 3.7
          TRAVIS_USE_NOX: 0
          DEFAULT_OPTIONAL_DEPENDENCY: "OFF"
          BUILD_SHARED_LIB: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL: ""
         ## Tests using PIP
         # Build and run tests without all optional dependencies (default behavior) and
         # use nox
        - os: ubuntu-20.04
          OS_PYTHON_VERSION: 3.8
          TRAVIS_USE_NOX: 1
          DEFAULT_OPTIONAL_DEPENDENCY: "OFF"
          BUILD_SHARED_LIB: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL: ""
        - os: ubuntu-18.04
          OS_PYTHON_VERSION: 3.6
          TRAVIS_USE_NOX: 1
          DEFAULT_OPTIONAL_DEPENDENCY: "OFF"
          BUILD_SHARED_LIB: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL: ""
        - os: "macos-10.15"
          OS_PYTHON_VERSION: 3.7
          TRAVIS_USE_NOX: 1
          DEFAULT_OPTIONAL_DEPENDENCY: "OFF"
          BUILD_SHARED_LIB: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS: "OFF"
          OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL: ""

    runs-on: ${{ matrix.os }}
    env:
      OPEN_SPIEL_ENABLE_JAX: ON
      OPEN_SPIEL_ENABLE_PYTORCH: ON
      OPEN_SPIEL_ENABLE_TENSORFLOW: ON
      OPEN_SPIEL_ENABLE_PYTHON_MISC: ON
      OS_PYTHON_VERSION: ${{ matrix.OS_PYTHON_VERSION }}
      TRAVIS_USE_NOX:  ${{ matrix.TRAVIS_USE_NOX }}
      DEFAULT_OPTIONAL_DEPENDENCY: ${{ matrix.DEFAULT_OPTIONAL_DEPENDENCY }}
      OPEN_SPIEL_BUILD_WITH_JULIA: ${{ matrix.OPEN_SPIEL_BUILD_WITH_JULIA }}
      BUILD_SHARED_LIB:  ${{ matrix.BUILD_SHARED_LIB }}
      OPEN_SPIEL_BUILD_WITH_ORTOOLS:  ${{ matrix.OPEN_SPIEL_BUILD_WITH_ORTOOLS }}
      OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL:  ${{ matrix.OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL }}

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        pwd
        chmod +x install.sh
        ./install.sh
    - name: Build and test
      run: |
        python3 --version
        ./open_spiel/scripts/travis_script.sh
